export type Deck = {
  id: string
  name: string
  emoji: string
  color: string
  description?: string
  words: string[]
  custom?: boolean
}

export const ALL_DECKS: Deck[] = [
  {
    id: 'starter',
    name: 'Starter Pack',
    emoji: '🎉',
    color: '#F2B705',
    description: 'Quick, easy, and fun party warm-up cards',
    words: [
      'Elephant',
      'Pizza',
      'Guitar',
      'Rainbow',
      'Astronaut',
      'Bicycle',
      'Volcano',
      'Penguin',
      'Firefighter',
      'Rollercoaster',
      'Helicopter',
      'Telescope',
      'Submarine',
      'Campfire',
      'Fireworks',
      'Pyramid',
      'Kangaroo',
      'Cupcake',
      'Sunglasses',
      'Snowman'
    ]
  },
  {
    id: 'movies-tv',
    name: 'Movies & Series',
    emoji: '🎬',
    color: '#E8453C',
    description: 'Blockbuster English, Bollywood & Bangladeshi cinema and hit series',
    words: [
      'Beder Meye Josna',
      'Hawa',
      'Priyotoma',
      'Toofan',
      'Aynabaji',
      'Monpura',
      'Dipu Number Two',
      'Matir Moina (The Clay Bird)',
      'Debi',
      'Dhaka Attack',
      'Poran',
      'Shurongo',
      'Jibon Theke Neya',
      'Bachelor',
      'Guerrilla',
      'Poramon 2',
      'Hothat Brishti',
      'Keyamot Theke Keyamot',
      'Den Mohor',
      'Antore Antore',
      'Lal Shalu',
      'Padma Nadir Majhi',
      'Hason Raja',
      'Taqdeer',
      'Karagar',
      'Dilwale Dulhania Le Jayenge (DDLJ)',
      'Sholay',
      '3 Idiots',
      'Kabhi Khushi Kabhie Gham (K3G)',
      'Dangal',
      'Kuch Kuch Hota Hai',
      'Lagaan',
      'Kal Ho Naa Ho',
      'Zindagi Na Milegi Dobara (ZNMD)',
      'Taare Zameen Par',
      'Dil Chahta Hai',
      'PK',
      'Bajrangi Bhaijaan',
      'Chennai Express',
      'Om Shanti Om',
      'Gangs of Wasseypur',
      'Andhadhun',
      'Chak De! India',
      'Don (Shah Rukh Khan)',
      'Krrish',
      'Dhoom 2',
      'Jab We Met',
      'Swades',
      'Munna Bhai M.B.B.S.',
      'Lage Raho Munna Bhai',
      'Hera Pheri',
      'Phir Hera Pheri',
      'Golmaal',
      'Welcome',
      'Yeh Jawaani Hai Deewani (YJHD)',
      'Queen',
      'Stree',
      'Jawan',
      'Pathaan',
      'Animal',
      '12th Fail',
      'Drishyam',
      'Kabir Singh',
      'Sacred Games',
      'Mirzapur',
      'The Family Man',
      'Scam 1992: The Harshad Mehta Story',
      'Harry Potter',
      'Titanic',
      'The Avengers',
      'Inception',
      'The Dark Knight',
      'Interstellar',
      'Avatar',
      'The Lord of the Rings',
      'Jurassic Park',
      'Star Wars',
      'The Matrix',
      'The Godfather',
      'Oppenheimer',
      'Barbie',
      'Spider-Man',
      'Gladiator',
      'The Lion King',
      'Forrest Gump',
      'Superman',
      'Pirates of the Caribbean',
      'Batman',
      'Home Alone',
      'Iron Man',
      'Fight Club',
      'The Prestige',
      'Fast & Furious',
      'John Wick',
      'Dune',
      'Deadpool & Wolverine',
      'Stranger Things',
      'Breaking Bad',
      'Game of Thrones',
      'Squid Game',
      'Money Heist',
      'Friends',
      'The Office',
      'Sherlock',
      'The Dark Night Rises'
    ]
  },
  {
    id: 'act-it-out',
    name: 'Act It Out',
    emoji: '🎭',
    color: '#8B5CF6',
    description: 'No talking allowed! Act out funny actions and scenarios',
    words: [
      'Brushing your teeth',
      'Walking on a rope',
      'Opening a bottle',
      'Stuck in heavy traffic',
      'Surfing a huge wave',
      'Walking on the Moon',
      'Riding a crazy rollercoaster',
      'Sneezing',
      'Eating a pizza slice',
      'Eating extremely spicy chili',
      'Milking a cow',
      'Playing a guitar',
      'Solving a puzzle',
      'Skiing down a steep mountain',
      'Getting caught in torrential rain',
      'Taking a flattering selfie',
      'Riding a bike',
      'Running away from a bee',
      'Singing loudly in the shower',
      'Zombie walking',
      'Juggling flaming torches',
      'Sumo wrestling match',
      'Changing a baby diaper',
      'Walking against strong wind',
      'Dancing ballet',
      'Winning the lottery jackpot',
      'Opening a jar',
      'Karate kicking',
      'Escaping quicksand',
      'Bus conductor',
      'Tasting sour lemon',
      'Arm wrestling',
      'Walking on hot weather',
      'Bowling a strike',
      'Hypnotizing someone',
      'Putting on makeup',
      'Crying',
      'Looking for someone',
      'Figting with someone',
      'Swimming in a pool',
      'Taking a Bath',
      'Smoking',
      'Sleeping'
    ]
  },
  {
    id: 'animals-nature',
    name: 'Animals & Wildlife',
    emoji: '🦁',
    color: '#1E9E6A',
    description: 'From deep sea creatures to jungle predators',
    words: [
      'Lion',
      'Kangaroo',
      'Penguin',
      'African Elephant',
      'Chimpanzee',
      'Bottlenose Dolphin',
      'Giraffe',
      'Sloth',
      'Rat',
      'Giant Octopus',
      'Cheetah',
      'Giant Panda',
      'Koala',
      'Peacock',
      'Crocodile',
      'Silverback Gorilla',
      'Zebra',
      'Great Horned Owl',
      'Human',
      'Seahorse',
      'Polar Bear',
      'Platypus',
      'Buffalo ',
      'Shark',
      'Bald Eagle',
      'Parrot',
      'Turtle',
      'Cuckoos',
      'Wolf',
      'Hippopotamus',
      'Komodo Dragon',
      'Hummingbird',
      'Snake',
      'Grizzly Bear',
      'Ostrich',
      'Blue Whale',
      'Jellyfish',
      'Red Fox',
      'Monkey',
      'Tiger',
      'Crow',
      'Camel',
      'Squid',
      'Orca',
      'Mongoose',
      'Duck',
      'Goose'
    ]
  },
  {
    id: 'celebrities',
    name: 'Superstars & Icons',
    emoji: '🌟',
    color: '#D6336C',
    description: 'Legends, icons, and superstars from South Asia and across the globe',
    words: [
      'Shakib Al Hasan',
      'Mashrafe Bin Mortaza',
      'Tamim Iqbal',
      'Mushfiqur Rahim',
      'Mustafizur Rahman',
      'Humayun Ahmed',
      'James (Nagar Baul)',
      'Ayub Bachchu',
      'Runa Laila',
      'Sabina Yasmin',
      'Chanchal Chowdhury',
      'Mosharraf Karim',
      'Shakib Khan',
      'Salman Shah',
      'Jaya Ahsan',
      'Tahsan Khan',
      'Asif Akbar',
      'Habibul Bashar',
      'Sachin Tendulkar',
      'Virat Kohli',
      'MS Dhoni',
      'Rohit Sharma',
      'Shah Rukh Khan',
      'Amitabh Bachchan',
      'Salman Khan',
      'Aamir Khan',
      'Arijit Singh',
      'Lata Mangeshkar',
      'A.R. Rahman',
      'Shreya Ghoshal',
      'Kishore Kumar',
      'Deepika Padukone',
      'Priyanka Chopra',
      'Rajinikanth',
      'Hrithik Roshan',
      'Kapil Dev',
      'Sourav Ganguly',
      'Sania Mirza',
      'Alia Bhatt',
      'Shahid Afridi',
      'Atif Aslam',
      'Babar Azam',
      'Wasim Akram',
      'Imran Khan',
      'Shoaib Akhtar',
      'Rahat Fateh Ali Khan',
      'Cristiano Ronaldo',
      'Lionel Messi',
      'Taylor Swift',
      'Michael Jackson',
      'Tom Cruise',
      'Leonardo DiCaprio',
      'Dwayne "The Rock" Johnson',
      'Elon Musk',
      'MrBeast',
      'Jackie Chan',
      'Eminem',
      'Justin Bieber',
      'Selena Gomez',
      'Beyoncé',
      'Rihanna',
      'Keanu Reeves',
      'Brad Pitt',
      'David Beckham',
      'Gordon Ramsay',
      'Morgan Freeman',
      'Adele',
      'Ed Sheeran',
      'Bruno Mars',
      'Billie Eilish',
      'Michael jackson',
      'John Cena',
      'Undertaker',
      'Donald Trump',
      'Barack Obama',
      'William Shakespeare',
      'Albert Einstein',
      'Isaac Newton',
      'Charlie Chaplin',
      'Adolf Hitler',
      'Muhammad Ali'
    ]
  },
  {
    id: 'food-drinks',
    name: 'Food & Drinks',
    emoji: '🍕',
    color: '#F0803C',
    description: 'Mouth-watering dishes, snacks, and beverages',
    words: [
      'Pizza Margherita',
      'Sushi & Sashimi',
      'Chocolate Ice Cream',
      'Crispy Tacos',
      'French Fries',
      'Pancakes with Maple Syrup',
      'Boba Bubble Tea',
      'Double Cheeseburger',
      'Hot Espresso',
      'Spaghetti Bolognese',
      'Guacamole and Tortilla Chips',
      'Fluffy Cotton Candy',
      'Butter Croissant',
      'Japanese Ramen',
      'Chicago Hot Dog',
      'Sweet Watermelon',
      'Spicy Burrito',
      'Glazed Donuts',
      'Avocado Toast',
      'Barbecue Ribs',
      'Buttery Popcorn',
      'Cinnamon Churros',
      'Belgian Waffles',
      'Chicken Nuggets',
      'Lasagna',
      'Fish and Chips',
      'Chocolate Milkshake',
      'Pad Thai',
      'Fresh Dim Sum',
      'Cheese Fondue',
      'Biryani',
      'Falafel',
      'Samosa',
      'Tiramisu',
      'Smoothie Bowl'
    ]
  },
  {
    id: 'world-travel',
    name: 'World Landmarks',
    emoji: '🌍',
    color: '#0E9BA6',
    description: 'Famous monuments, natural wonders, and great cities',
    words: [
      'Eiffel Tower (Paris)',
      'Statue of Liberty (New York)',
      'Great Wall of China',
      'Taj Mahal (India)',
      'Great Pyramids of Giza',
      'Colosseum (Rome)',
      'London',
      'Mount Everest',
      "Cox's Bazar",
      'Sundarban',
      'Mount Fuji (Japan)',
      'Sreemongol',
      'Amazon River',
      'Neil River',
      'Burj Khalifa (Dubai)',
      'Sahara Desert',
      'Kashmir',
      'Panjab',
      'Hollywood Sign (Los Angeles)',
      'Petra (Jordan)',
      'Bandarban',
      'Bagdad',
      'Tehran',
      'Mecca',
      'Madina',
      'Riyad'
    ]
  },
  {
    id: 'bd-brands',
    name: 'Brands in Bangladesh',
    emoji: '🛍️',
    color: '#2563EB',
    description: 'Famous Bangladeshi & multinational brands, fashion, telecom, food & tech',
    words: [
      'Grameenphone (GP)',
      'Banglalink',
      'Robi',
      'Teletalk',
      'bKash',
      'Nagad',
      'Pathao',
      'Foodpanda',
      'Daraz',
      'Chaldal',
      'Shwapno',
      'Aarong',
      'Pran',
      'Radhuni',
      'Fresh (Meghna Group)',
      'Teer (City Group)',
      'Akij',
      'Ispahani Mirzapore Tea',
      'Milk Vita',
      'Aarong Dairy',
      'Mojo',
      'Frutika',
      'Olympic Biscuits',
      'Dan Cake',
      'Igloo Ice Cream',
      'Polar Ice Cream',
      'KFC',
      'Pizza Hut',
      'Burger King',
      "Domino's Pizza",
      "Gloria Jean's Coffees",
      'North End Coffee',
      'Walton',
      'Singer',
      'Vision Electronics',
      'Marcel',
      'Minister',
      'Symphony Mobile',
      'Samsung',
      'Apple (iPhone)',
      'Xiaomi',
      'Apex Footwear',
      'Bata',
      'Lotto',
      'Bay Emporium',
      'Yellow (Beximco)',
      'Sailor',
      'Cats Eye',
      'Ecstasy',
      'Richman',
      'Le Reve',
      'Gentle Park',
      'Taaga',
      'Kay Kraft',
      'Square Pharmaceuticals',
      'Beximco Pharma',
      'Savlon (ACI)',
      'Meril',
      'Tibbet Snow',
      'Sandalina Soap',
      'Parachute Coconut Oil',
      'Bashundhara Group',
      'RFL Plastics',
      'Gazi Group',
      'Runner Automobiles',
      'Green Line Paribahan',
      'Hanif Enterprise',
      'Shyamoli Paribahan',
      'Shohoz',
      'Unimart',
      'Meena Bazar',
      'Agora'
    ]
  }
]
